// « Qui de nous deux ? » : 200 questions originales, en 10 thèmes.
// Écrites pour l'application, en évitant les classiques trop simples (qui ronfle, qui oublie ses clés…).

export type WhoCategory = { id: string; emoji: string; title: string; adult: boolean; questions: string[] };

export const WHO_OF_US_CATEGORIES: WhoCategory[] = [
  {
    id: "mauvaise-foi",
    emoji: "🙃",
    title: "Mauvaise foi & petites manies",
    adult: false,
    questions: [
      "Qui refuserait d'admettre une erreur, même devant une vidéo qui le prouve ?",
      "Qui dit « j'arrive dans cinq minutes » sans être encore habillé·e ?",
      "Qui remet un pot vide au frigo en espérant que l'autre ne remarque rien ?",
      "Qui lâche « je ne suis pas fâché·e » sur un ton qui prouve exactement le contraire ?",
      "Qui se souvient mot pour mot d'une dispute d'il y a trois ans ?",
      "Qui pourrait débattre vingt minutes pour avoir raison sur un détail sans importance ?",
      "Qui répond « comme tu veux », puis refuse toutes les propositions ?",
      "Qui accuse le GPS dès qu'on se perd ?",
      "Qui abandonne un jeu de société dès qu'il commence à perdre ?",
      "Qui mange la dernière part en disant « je pensais que tu n'en voulais plus » ?",
      "Qui jure avoir « juste reposé ses yeux » après une sieste de deux heures ?",
      "Qui range un objet si bien que plus personne ne le retrouve jamais ?",
      "Qui fait semblant d'avoir lu un livre pour briller en soirée ?",
      "Qui change les règles d'un jeu en pleine partie ?",
      "Qui trouverait une excuse pour ne pas sortir la poubelle, même si elle déborde ?",
      "Qui dit « on verra » pour dire non sans le dire ?",
      "Qui cache un achat en le déballant en douce ?",
      "Qui garde 47 onglets ouverts « au cas où » ?",
      "Qui ment sur l'heure à laquelle il ou elle s'est couché·e ?",
      "Qui accuse le chat (ou le voisin) d'un bruit suspect qu'il ou elle a fait ?",
    ],
  },
  {
    id: "catastrophe",
    emoji: "🧟",
    title: "Scénarios catastrophe",
    adult: false,
    questions: [
      "Qui survivrait le moins longtemps dans un film d'horreur ?",
      "Qui ouvrirait la porte de la cave alors que tout le monde crie de ne pas le faire ?",
      "Qui deviendrait chef·fe d'une petite tribu après l'apocalypse ?",
      "Qui essaierait d'apprivoiser un zombie ?",
      "Qui paniquerait le plus pendant une coupure d'internet de 24 heures ?",
      "Qui mangerait les réserves de survie « juste pour goûter » ?",
      "Qui négocierait avec des extraterrestres… et se ferait avoir ?",
      "Qui se perdrait dans un magasin de meubles au point d'y passer la nuit ?",
      "Qui craquerait le premier, coincé·e dans un ascenseur pendant trois heures ?",
      "Qui survivrait sur une île déserte grâce à sa débrouillardise ?",
      "Qui partirait seul·e enquêter sur un bruit bizarre à 3 h du matin ?",
      "Qui resterait calme pendant un tremblement de terre, mais hurlerait devant une araignée ?",
      "Qui se ferait éliminer d'une émission de survie dès le premier épisode ?",
      "Qui sauverait la machine à café avant les albums photo en cas d'incendie ?",
      "Qui finirait par sympathiser avec le méchant d'un film d'action ?",
      "Qui ferait exploser le micro-ondes en réchauffant un plat ?",
      "Qui saurait faire du feu sans allumettes ?",
      "Qui inventerait une religion si on restait naufragés trop longtemps ?",
      "Qui serait enlevé·e par des extraterrestres puis rendu·e parce qu'il ou elle parle trop ?",
      "Qui tiendrait le plus longtemps sans téléphone ?",
    ],
  },
  {
    id: "cinema",
    emoji: "🎬",
    title: "Notre vie en film",
    adult: false,
    questions: [
      "Qui finirait dans une téléréalité et se ferait éliminer pour drama ?",
      "Qui deviendrait viral·e pour une raison complètement ridicule ?",
      "Qui ferait tout rater pendant un braquage ?",
      "Qui gagnerait un jeu télévisé grâce à des connaissances totalement inutiles ?",
      "Qui serait démasqué·e en premier en tant qu'espion·ne ?",
      "Qui donnerait l'interview la plus catastrophique au journal télévisé ?",
      "Qui deviendrait influenceur·se sur un sujet improbable ?",
      "Qui ferait un discours de remerciement beaucoup trop long aux Oscars ?",
      "Qui jouerait le rôle du méchant dans le film de notre vie ?",
      "Qui serait le plus crédible en gourou d'une secte du bien-être ?",
      "Qui se ferait arrêter pour un crime ridicule, comme voler un panneau de signalisation ?",
      "Qui écrirait son autobiographie sans que personne ne l'ait demandée ?",
      "Qui se ferait reconnaître dans la rue à cause d'un mème ?",
      "Qui tomberait dans une caméra cachée sans jamais comprendre ?",
      "Qui accepterait un jeu télévisé humiliant pour 500 € ?",
      "Qui deviendrait président·e par accident ?",
      "Qui serait le personnage qui dit « séparons-nous » dans un film d'horreur ?",
      "Qui pourrait tromper un détecteur de mensonges sans transpirer ?",
      "Qui finirait en prison et deviendrait chef·fe de la cantine ?",
      "Qui ferait le meilleur méchant de dessin animé ?",
    ],
  },
  {
    id: "quotidien",
    emoji: "🛋️",
    title: "Quotidien absurde",
    adult: false,
    questions: [
      "Qui parle aux objets quand ils ne fonctionnent pas ?",
      "Qui gagne des disputes imaginaires sous la douche ?",
      "Qui ouvre le frigo cinq fois en espérant qu'un nouveau plat soit apparu ?",
      "Qui a déjà répondu « vous aussi » à un serveur qui souhaitait bon appétit ?",
      "Qui pourrait s'endormir debout dans les transports ?",
      "Qui garde un sac rempli de sacs depuis des années ?",
      "Qui donne des prénoms aux plantes de la maison ?",
      "Qui danse seul·e dans la cuisine quand personne ne regarde ?",
      "Qui a une théorie du complot préférée ?",
      "Qui parle à un animal comme à un collègue de bureau ?",
      "Qui cherche ses lunettes alors qu'elles sont sur sa tête ?",
      "Qui prend un accent étranger sans s'en rendre compte après un voyage ?",
      "Qui se réveille à 3 h du matin avec une idée d'entreprise « géniale » ?",
      "Qui lit les notices de montage, et qui les jette directement ?",
      "Qui tient de vraies conversations avec lui-même ou elle-même, à voix haute ?",
      "Qui répond au salut d'un inconnu qui saluait en fait quelqu'un derrière ?",
      "Qui pourrait passer une heure au rayon des bougies parfumées ?",
      "Qui a toujours les poches pleines de tickets de caisse ?",
      "Qui transforme n'importe quelle corvée en compétition ?",
      "Qui chante des paroles complètement inventées avec une totale assurance ?",
    ],
  },
  {
    id: "voyage",
    emoji: "✈️",
    title: "Voyages & aventures",
    adult: false,
    questions: [
      "Qui oublierait son passeport le jour du départ ?",
      "Qui ferait un tableau Excel pour des vacances « improvisées » ?",
      "Qui commanderait le plat le plus étrange du menu sans demander ce que c'est ?",
      "Qui se ferait arnaquer par un vendeur de souvenirs, et serait ravi·e quand même ?",
      "Qui rapporterait l'objet le plus inutile d'un voyage ?",
      "Qui parlerait avec les mains dans un pays dont il ou elle ignore la langue ?",
      "Qui raterait l'avion pour finir son café ?",
      "Qui deviendrait ami·e avec tout le camping en 24 heures ?",
      "Qui partirait faire le tour du monde sur un coup de tête ?",
      "Qui prendrait 300 photos du même coucher de soleil ?",
      "Qui réussirait à se perdre… avec le GPS allumé ?",
      "Qui insisterait pour la randonnée « facile » qui dure finalement huit heures ?",
      "Qui sympathiserait avec un animal sauvage un peu trop près ?",
      "Qui réserverait l'hôtel le moins cher, et le regretterait toute la nuit ?",
      "Qui accepterait un dîner chez des inconnus à l'autre bout du monde ?",
      "Qui rapporterait des kilos de nourriture locale dans sa valise ?",
      "Qui jouerait les touristes dans sa propre ville ?",
      "Qui inventerait une fausse anecdote de voyage pour impressionner ?",
      "Qui négocierait le prix d'un objet qu'il ou elle ne veut même pas ?",
      "Qui monterait dans le mauvais train avec une confiance absolue ?",
    ],
  },
  {
    id: "gourmandise",
    emoji: "🍝",
    title: "Gourmandise & excès",
    adult: false,
    questions: [
      "Qui pourrait manger des pâtes à tous les repas pendant un mois ?",
      "Qui finit les restes directement dans la casserole ?",
      "Qui se lèverait en pleine nuit pour manger du fromage ?",
      "Qui commande toujours le même plat, même dans un nouveau restaurant ?",
      "Qui arriverait à faire brûler de l'eau ?",
      "Qui vole des frites dans l'assiette de l'autre en jurant que non ?",
      "Qui invente une recette improbable avec les restes du frigo ?",
      "Qui boude parce que l'autre a mangé son dessert ?",
      "Qui mangerait un gâteau entier « par accident » ?",
      "Qui regarde des vidéos de cuisine sans jamais cuisiner ?",
      "Qui serait éliminé·e au premier tour d'un concours de cuisine ?",
      "Qui note chaque plat sur 10 comme un critique gastronomique ?",
      "Qui garde des sachets de sauce de fast-food dans un tiroir ?",
      "Qui goûterait un insecte grillé sans hésiter ?",
      "Qui ferait un régime pendant exactement une matinée ?",
      "Qui pourrait vivre uniquement de céréales ?",
      "Qui critique la cuisine de l'autre… et en reprend trois fois ?",
      "Qui transformerait un dîner romantique en concours de mangeurs ?",
      "Qui cache des bonbons dans des endroits stratégiques de la maison ?",
      "Qui ose dire que l'ananas sur la pizza, c'est délicieux ?",
    ],
  },
  {
    id: "numerique",
    emoji: "📱",
    title: "Vie numérique",
    adult: false,
    questions: [
      "Qui envoie des messages vocaux de huit minutes ?",
      "Qui retrouverait le profil de n'importe qui en 30 secondes chrono ?",
      "Qui aimerait une photo de 2015 par accident en espionnant un profil ?",
      "Qui vit sereinement avec des centaines de notifications non lues ?",
      "Qui peut passer une nuit entière à enchaîner des vidéos absurdes ?",
      "Qui programme dix alarmes avant de se lever ?",
      "Qui écrit des messages avec beaucoup trop d'émojis ?",
      "Qui relit dix fois un message avant de l'envoyer ?",
      "Qui garde des captures d'écran comme preuves en cas de désaccord ?",
      "Qui achète un objet totalement inutile à cause d'une publicité ?",
      "Qui laisse sonner son téléphone pour éviter un appel ?",
      "Qui parle à l'assistant vocal comme à un vieil ami ?",
      "Qui a déjà envoyé un message gênant à la mauvaise personne ?",
      "Qui a le fond d'écran le plus embarrassant ?",
      "Qui deviendrait accro à un jeu mobile ridicule ?",
      "Qui lancerait un live sans faire exprès ?",
      "Qui lit vraiment les conditions générales d'utilisation ?",
      "Qui perd à un jeu vidéo et accuse la manette ?",
      "Qui a encore la même photo de profil depuis dix ans ?",
      "Qui a plus de 20 000 photos dans son téléphone, dont 90 % de captures d'écran ?",
    ],
  },
  {
    id: "dans-40-ans",
    emoji: "👵",
    title: "Dans 40 ans",
    adult: false,
    questions: [
      "Qui deviendra le petit vieux ou la petite vieille qui raconte toujours la même histoire ?",
      "Qui se mettra au tricot avec une passion inquiétante ?",
      "Qui fera la morale aux jeunes sur leurs téléphones… depuis son téléphone ?",
      "Qui tiendra le potager comme une mission militaire ?",
      "Qui deviendra la star du club de loto ?",
      "Qui partira en camping-car sans prévenir personne ?",
      "Qui dansera encore à toutes les fêtes à 80 ans ?",
      "Qui se disputera avec les voisins pour une haie mal taillée ?",
      "Qui portera des chaussettes avec des sandales sans aucune honte ?",
      "Qui écrira ses mémoires en trois tomes ?",
      "Qui adoptera dix chats ?",
      "Qui sera encore en retard à son propre anniversaire de 80 ans ?",
      "Qui deviendra accro aux mots croisés ?",
      "Qui osera une couleur de cheveux improbable pour la retraite ?",
      "Qui racontera notre histoire d'amour avec beaucoup trop de détails ?",
      "Qui sera le chouchou des infirmières ?",
      "Qui conduira encore trop vite à 85 ans ?",
      "Qui organisera une fête pour nos 50 ans ensemble ?",
      "Qui refusera catégoriquement toute nouvelle technologie ?",
      "Qui fera du parachute pour ses 70 ans ?",
    ],
  },
  {
    id: "nous",
    emoji: "💞",
    title: "Nous deux",
    adult: false,
    questions: [
      "Qui a craqué en premier ?",
      "Qui a envoyé le premier message après notre rencontre ?",
      "Qui se souvient de ce que l'autre portait au premier rendez-vous ?",
      "Qui garde rancune le plus longtemps après une dispute ?",
      "Qui fait le premier pas pour se réconcilier ?",
      "Qui a le plus de surnoms ridicules pour l'autre ?",
      "Qui pleurerait le plus à notre mariage ?",
      "Qui organise les surprises les plus folles ?",
      "Qui ferait une demande en mariage complètement ratée ?",
      "Qui se vante le plus de notre couple auprès des amis ?",
      "Qui imite le mieux l'autre ?",
      "Qui connaît par cœur les manies de l'autre ?",
      "Qui vole la couverture toute la nuit, sans jamais l'admettre ?",
      "Qui choisit le film… et s'endort au bout de dix minutes ?",
      "Qui ferait n'importe quoi pour faire rire l'autre ?",
      "Qui serait jaloux·se d'un personnage de série ?",
      "Qui oublie les dates importantes, pendant que l'autre les note partout ?",
      "Qui aurait parié sur notre couple dès le premier jour ?",
      "Qui serait le parent qui dit oui à tout ?",
      "Qui garde précieusement les tickets de nos sorties ?",
    ],
  },
  {
    id: "piquant",
    emoji: "🌶️",
    title: "Un peu piquant",
    adult: true,
    questions: [
      "Qui envoie les messages les plus suggestifs en pleine journée ?",
      "Qui rougit le plus facilement ?",
      "Qui a le regard qui en dit trop en public ?",
      "Qui résiste le moins bien à un câlin quand l'autre travaille ?",
      "Qui lancerait un jeu coquin au pire moment ?",
      "Qui porterait une tenue audacieuse juste pour voir la réaction de l'autre ?",
      "Qui sait exactement quoi dire pour faire craquer l'autre ?",
      "Qui fait les massages qui finissent rarement en simple massage ?",
      "Qui raterait un strip-tease en se prenant les pieds dans son pantalon ?",
      "Qui a le plus d'imagination pour les surprises intimes ?",
      "Qui embrasserait l'autre dans un ascenseur bondé ?",
      "Qui se laisse le plus distraire par l'autre sous la douche ?",
      "Qui a le fou rire au moment le moins approprié ?",
      "Qui proposerait une nuit à l'hôtel juste pour changer de décor ?",
      "Qui est le plus tactile en public ?",
      "Qui flirte avec l'autre en plein repas de famille ?",
      "Qui garde une lettre d'amour enflammée cachée quelque part ?",
      "Qui danse de façon séduisante sans même s'en rendre compte ?",
      "Qui est le plus difficile à surprendre ?",
      "Qui ferait l'aveu le plus surprenant après un verre de trop ?",
    ],
  },
];

/** Anciennes questions par défaut, jugées trop simples : retirées si personne n'y a encore répondu. */
export const LEGACY_WHO_OF_US = [
  "Qui est le plus susceptible d'oublier ses clés ?",
  "Qui est le plus susceptible de pleurer devant un film ?",
  "Qui est le plus susceptible de partir en voyage sur un coup de tête ?",
  "Qui est le plus susceptible d'être en retard ?",
  "Qui est le plus susceptible de finir le plat de l'autre ?",
  "Qui est le plus susceptible de se perdre sans GPS ?",
  "Qui est le plus susceptible d'adopter un animal sans prévenir ?",
  "Qui est le plus susceptible de lancer une discussion à 2 h du matin ?",
  "Qui est le plus susceptible de gagner à un jeu de société ?",
  "Qui est le plus susceptible de planifier les vacances un an à l'avance ?",
];

/** Questions mélangées entre thèmes (1 de chaque thème à tour de rôle) pour varier dès le début. */
export function interleavedWhoQuestions() {
  const longest = Math.max(...WHO_OF_US_CATEGORIES.map((c) => c.questions.length));
  const out: { prompt: string; category: string }[] = [];
  for (let i = 0; i < longest; i++) {
    for (const category of WHO_OF_US_CATEGORIES) {
      const prompt = category.questions[i];
      if (prompt) out.push({ prompt, category: category.id });
    }
  }
  return out;
}
